### ISSUE TITLE
"special" file names with extended Unicode characters can lead to traceback

### ISSUE THREAD

**Issue by wkloucek** [cs3org/wopiserver#124]
```
wopi-wopiserver-7c79c74b7c-6vksp wopiserver {"time": "2023-06-23T15:51:03.816", "host": "wopi-wopiserver-7c79c74b7c-6vksp", "level": "ERROR", "process": "waitress", Exception while serving /wopi/iop/download}
wopi-wopiserver-7c79c74b7c-6vksp wopiserver Traceback (most recent call last):
wopi-wopiserver-7c79c74b7c-6vksp wopiserver   File "/usr/local/lib/python3.11/site-packages/waitress/channel.py", line 428, in service
wopi-wopiserver-7c79c74b7c-6vksp wopiserver     task.service()
wopi-wopiserver-7c79c74b7c-6vksp wopiserver   File "/usr/local/lib/python3.11/site-packages/waitress/task.py", line 168, in service
wopi-wopiserver-7c79c74b7c-6vksp wopiserver     self.execute()
wopi-wopiserver-7c79c74b7c-6vksp wopiserver   File "/usr/local/lib/python3.11/site-packages/waitress/task.py", line 472, in execute
wopi-wopiserver-7c79c74b7c-6vksp wopiserver     self.write(chunk)
wopi-wopiserver-7c79c74b7c-6vksp wopiserver   File "/usr/local/lib/python3.11/site-packages/waitress/task.py", line 306, in write
wopi-wopiserver-7c79c74b7c-6vksp wopiserver     rh = self.build_response_header()
wopi-wopiserver-7c79c74b7c-6vksp wopiserver          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wopi-wopiserver-7c79c74b7c-6vksp wopiserver   File "/usr/local/lib/python3.11/site-packages/waitress/task.py", line 279, in build_response_header
wopi-wopiserver-7c79c74b7c-6vksp wopiserver     return res.encode("latin-1")
wopi-wopiserver-7c79c74b7c-6vksp wopiserver            ^^^^^^^^^^^^^^^^^^^^^
wopi-wopiserver-7c79c74b7c-6vksp wopiserver UnicodeEncodeError: 'latin-1' codec can't encode character '\u0308' in position 80: ordinal not in range(256)
```

**Comment by glpatcern** [comment]
> Could be this line:

How do you determine that it's that line from a stack trace that does not include the `getFile()` function?

**Comment by glpatcern** [comment]
OK, so actually _your_ log is more useful - I didn't see the `/wopi/iop/download` endpoint in my logs!

Then yes, it's likely the place that triggers the error, though still in a way that does not expose the stack trace. I can see if there's anything to "sanitize" a filename, but I'm afraid that any manipulation of such an invalid Unicode string would trigger this exception anyway.

**Comment by glpatcern** [comment]
Thanks for this investigation. Concerning why `/wopi/iop/download` even gets called, the answer is in https://github.com/cs3org/wopiserver/blob/master/src/core/wopi.py#L77-L78

And yes, it looks like url-encoding the header may fix it. I'll give it a try.
