### ISSUE TITLE
cs3org/wopiserver:latest cannot start due to missing 'cs3.identity.group'

### ISSUE THREAD

**Issue by SamuAlfageme** [cs3org/wopiserver#31]
```
kubectl logs iop-wopiserver-794ffb74c8-w8h9v
Missing module when attempting to import cs3iface.py. Please make sure dependencies are met.
Traceback (most recent call last):
  File "/app/wopiserver.py", line 1077, in <module>
    Wopi.init()
  File "/app/wopiserver.py", line 89, in init
    storage_layer_import(cls.config.get('general', 'storagetype'))
  File "/app/wopiserver.py", line 52, in storage_layer_import
    storage = __import__(storagetype, globals(), locals())
  File "/app/cs3iface.py", line 19, in <module>
    import cs3.gateway.v1beta1.gateway_api_pb2_grpc as cs3gw_grpc
  File "/usr/local/lib/python3.9/site-packages/cs3/gateway/v1beta1/gateway_api_pb2_grpc.py", line 8, in <module>
    from cs3.gateway.v1beta1 import gateway_api_pb2 as cs3_dot_gateway_dot_v1beta1_dot_gateway__api__pb2
  File "/usr/local/lib/python3.9/site-packages/cs3/gateway/v1beta1/gateway_api_pb2.py", line 18, in <module>
    from cs3.identity.group.v1beta1 import group_api_pb2 as cs3_dot_identity_dot_group_dot_v1beta1_dot_group__api__pb2
ModuleNotFoundError: No module named 'cs3.identity.group'
```

**Comment by SamuAlfageme** [comment]
By reading the output from the CI on https://cloud.drone.io/cs3org/cs3apis/346/1/2 :

```
[touch cs3/__init__.py cs3/app/__init__.py cs3/app/provider/__init__.py cs3/app/provider/v1beta1/__init__.py cs3/app/registry/__init__.py cs3/app/registry/v1beta1/__init__.py cs3/auth/__init__.py cs3/auth/provider/__init__.py cs3/auth/provider/v1beta1/__init__.py cs3/auth/registry/__init__.py cs3/auth/registry/v1beta1/__init__.py cs3/gateway/__init__.py cs3/gateway/v1beta1/__init__.py cs3/identity/__init__.py cs3/identity/group/__init__.py cs3/identity/group/v1beta1/__init__.py cs3/identity/user/__init__.py cs3/identity/user/v1beta1/__init__.py cs3/ocm/__init__.py cs3/ocm/core/__init__.py cs3/ocm/core/v1beta1/__init__.py cs3/ocm/invite/__init__.py cs3/ocm/invite/v1beta1/__init__.py cs3/ocm/provider/__init__.py cs3/ocm/provider/v1beta1/__init__.py cs3/preferences/__init__.py cs3/preferences/v1beta1/__init__.py cs3/rpc/__init__.py cs3/rpc/v1beta1/__init__.py cs3/sharing/__init__.py cs3/sharing/collaboration/__init__.py cs3/sharing/collaboration/v1beta1/__init__.py cs3/sharing/link/__init__.py cs3/sharing/link/v1beta1/__init__.py cs3/sharing/ocm/__init__.py cs3/sharing/ocm/v1beta1/__init__.py cs3/storage/__init__.py cs3/storage/provider/__init__.py cs3/storage/provider/v1beta1/__init__.py cs3/storage/registry/__init__.py cs3/storage/registry/v1beta1/__init__.py cs3/tx/__init__.py cs3/tx/v1beta1/__init__.py cs3/types/__init__.py cs3/types/v1beta1/__init__.py]
```

The `cs3.identity.group` module was initialized but hasn't been synced with the contents of https://github.com/cs3org/python-cs3apis/tree/master/cs3/identity/group/v1beta1.
